# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#	Site settings
title: Fellowship Bible Church
email: office@fbctn.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fellowshipbiblechurch.org" # the base hostname & protocol for your site
logo_url: "http://1a35adac855f40326ab5-545fc5a361402074649dd8b0f6e40b7d.r37.cf2.rackcdn.com/uploaded/f/0e6222796_1495038121_fbc-logo-360px-hex-414141.png"
logo_width: 180
logo_height: 60
twitter_username: fbctn
github_username:  fellowshipnashville

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
 newsletters:
  output: true
  permalink: /:categories/:title.html

# Default settings
defaults:
 -
  scope:
   path: "" # an empty string here means all files in the project
   type: newsletters
  values:
   author: Fellowship Bible Church
   layout: "default"
   published: true
   future: true
